### ISSUE TITLE
Loading .tif stacks on Linux machines fails due to hard-coded file separator

### ISSUE THREAD

**Issue by kmdouglass** [MStefko/ImageInjectorPlugin#1]
It looks like the plugin has a hard-coded file separator character (see the error window below between the words "Desktop" and "simulation") that corresponds to Windows systems. This means it can't find the file in Linux (and probably not Mac either).

The fix would likely involve using `File.separator` from `java.io.File`, but I haven't looked at the source code yet.

![image_injector_error](https://user-images.githubusercontent.com/3697676/27196256-05f35634-520a-11e7-98b4-24acb1c0e4ae.png)

**Comment by MStefko** [comment]
Resolved in v0.0.2, the file separator was actually not necessary for `ij.io.Opener.openTiff()`
